export const requestSectionContent = {
  EN: {
    renderLoadingContent: {
      loadingText: "Please wait. We are on your request",
    },
    renderSubmitMessageContent: {
      successMessage: "Request made successfully",
      clientErrorMessage: "Error uploading. Please try again",
      serverErrorMessage: "Upload failed. Please try again",
      goBack: "go back",
    },
    renderRequestSectionContent: {
      heading: "Make a Request By",
      myFileText: "Your browser does not support the video tag",
      uploadVideoText: "Click here to upload your video",
      uploadThumbnailText: "Click here to upload your thumbnail",
      title_: "Title (required)",
      description_: "Description (required)",
      titlePlaceHolder: "Add a title that describes your video",
      descriptionPlaceHolder: "Tell viewers about your video",
      audience_: "Audience(required)",
      madeForKids: "Yes, made for kids",
      notMadeForKids: "No, not made for kids",
      visibility_: "Visibility (required)",
      selectVisibility: "Select Visibility",
      public_: "public",
      private_: "private",
      category: "Category (required)",
      selectCategory: "Select Category",
      creatorInvitationCode: "Creator Invitation Code (required)",
      creatorIdPlaceHolder:'creator id',
      submit: "Submit",
    },
  },
  HI: {
    renderLoadingContent: {
      loadingText: "कृपया प्रतीक्षा करें। हम आपके अनुरोध पर हैं",
    },
    renderSubmitMessageContent: {
      successMessage: "अनुरोध सफलतापूर्वक किया गया",
      clientErrorMessage: "अपलोड करने में त्रुटि. कृपया पुन: प्रयास करें",
      serverErrorMessage: "अपलोड विफल। कृपया पुन: प्रयास करें",
      goBack: "वापस जाओ",
    },
    renderRequestSectionContent: {
      heading: "द्वारा अनुरोध करें",
      myFileText: "आपका ब्राउज़र में वीडियो टैग समर्थित नहीं है",
      uploadVideoText: "अपना वीडियो अपलोड करने के लिए यहां क्लिक करें",
      uploadThumbnailText: "अपना थंबनेल अपलोड करने के लिए यहां क्लिक करें",
      title_: "शीर्षक (आवश्यक)",
      description_: "विवरण (आवश्यक)",
      titlePlaceHolder: "एक शीर्षक जोड़ें जो आपके वीडियो का वर्णन करता हो",
      descriptionPlaceHolder: "दर्शकों को अपने वीडियो के बारे में बताएं",
      audience_: "श्रोता(आवश्यक)",
      madeForKids: "हाँ, बच्चों के लिए बनाया गया है",
      notMadeForKids: "नहीं, बच्चों के लिए नहीं बनाया गया",
      visibility_: "दृश्यता (आवश्यक)",
      selectVisibility: "दृश्यता का चयन करें",
      public_: "जनता",
      private_: "निजी",
      category: "श्रेणी (आवश्यक)",
      selectCategory: "श्रेणी चुनना",
      creatorInvitationCode: "निर्माता आमंत्रण कोड (आवश्यक)",
      creatorIdPlaceHolder:'निर्माता आईडी',
      submit: "जमा करना",
    },
  },
  TE: {
    renderLoadingContent: {
      loadingText: "దయచేసి వేచి ఉండండి. మేము మీ అభ్యర్థనపై ఉన్నాము",
    },
    renderSubmitMessageContent: {
      successMessage: "అభ్యర్థన విజయవంతంగా చేయబడింది",
      clientErrorMessage: "అప్‌లోడ్ చేయడంలో లోపం. దయచేసి మళ్లీ ప్రయత్నించండి",
      serverErrorMessage: "అప్లోడ్ విఫలమైంది. దయచేసి మళ్లీ ప్రయత్నించండి",
      goBack: "వెనక్కి వెళ్ళు",
    },
    renderRequestSectionContent: {
      heading: "ద్వారా అభ్యర్థన చేయండి",
      myFileText: "మీ బ్రౌజర్ వీడియో ట్యాగ్‌కు మద్దతు ఇవ్వదు",
      uploadVideoText: "మీ వీడియోను అప్‌లోడ్ చేయడానికి ఇక్కడ క్లిక్ చేయండి",
      uploadThumbnailText:
        "మీ సూక్ష్మచిత్రాన్ని అప్‌లోడ్ చేయడానికి ఇక్కడ క్లిక్ చేయండి",
      title_: "శీర్షిక (అవసరం)",
      description_: "వివరణ (అవసరం)",
      titlePlaceHolder: "మీ వీడియోను వివరించే శీర్షికను జోడించండి",
      descriptionPlaceHolder: "మీ వీడియో గురించి వీక్షకులకు చెప్పండి",
      audience_: "ప్రేక్షకులు (అవసరం)",
      madeForKids: "అవును, పిల్లల కోసం రూపొందించబడింది",
      notMadeForKids: "లేదు, పిల్లల కోసం రూపొందించబడలేదు",
      visibility_: "దృశ్యమానత (అవసరం)",
      selectVisibility: "దృశ్యమానతను ఎంచుకోండి",
      public_: "ప్రజా",
      private_: "ప్రైవేట్",
      category: "వర్గం (అవసరం)",
      selectCategory: "వర్గం ఎంచుకోండి",
      creatorInvitationCode: "సృష్టికర్త ఆహ్వాన కోడ్ (అవసరం)",
      creatorIdPlaceHolder:'సృష్టికర్త id',
      submit: "సమర్పించండి",
    },
  },
  ZH: {
    renderLoadingContent: {
      loadingText: "請稍等。我們根據您的要求",
    },
    renderSubmitMessageContent: {
      successMessage: "請求成功",
      clientErrorMessage: "上傳錯誤。請再試一次",
      serverErrorMessage: "上傳失敗。請再試一次",
      goBack: "回去",
    },
    renderRequestSectionContent: {
      heading: "提出請求",
      myFileText: "您的瀏覽器不支援video標籤",
      uploadVideoText: "點擊此處上傳您的視頻",
      uploadThumbnailText: "點擊此處上傳您的縮圖",
      title_: "標題（必填）",
      description_: "描述（必填）",
      titlePlaceHolder: "添加描述您的影片的標題",
      descriptionPlaceHolder: "向觀眾介紹您的視頻",
      audience_: "觀眾(必填)",
      madeForKids: "是的，專為兒童設計",
      notMadeForKids: "不，不適合兒童",
      visibility_: "可見性（必填）",
      selectVisibility: "選擇可見性",
      public_: "民眾",
      private_: "私人的",
      category: "類別（必填）",
      selectCategory: "選擇類別",
      creatorInvitationCode: "創作者邀請碼（必填）",
      creatorIdPlaceHolder:'創建者ID',
      submit: "提交",
    },
  },
  ES: {
    renderLoadingContent: {
      loadingText: "Espere por favor. Estamos a tu pedido",
    },
    renderSubmitMessageContent: {
      successMessage: "Solicitud realizada con éxito",
      clientErrorMessage: "Error al cargar. Inténtalo de nuevo",
      serverErrorMessage: "Subida fallida. Inténtalo de nuevo",
      goBack: "regresa",
    },
    renderRequestSectionContent: {
      heading: "Hacer una solicitud por",
      myFileText: "Su navegador no soporta la etiqueta de vídeo",
      uploadVideoText: "Haz clic aquí para subir tu vídeo",
      uploadThumbnailText: "Haga clic aquí para cargar su miniatura",
      title_: "Título(requerido)",
      description_: "Descripción(requerido)",
      titlePlaceHolder: "Añade un título que describa tu vídeo.",
      descriptionPlaceHolder: "Cuéntales a los espectadores sobre tu video",
      audience_: "Audiencia (requerido)",
      madeForKids: "Si, hecho para niños",
      notMadeForKids: "No, no hecho para niños",
      visibility_: "Visibilidad (requerido)",
      selectVisibility: "Seleccionar visibilidad",
      public_: "público",
      private_: "privado",
      category: "Categoría (requerido)",
      selectCategory: "selecciona una categoría",
      creatorInvitationCode: "Código de invitación de creador (obligatorio)",
      creatorIdPlaceHolder:'identificación del creador',
      submit: "Entregar",
    },
  },
  FR: {
    renderLoadingContent: {
      loadingText: "S'il vous plaît, attendez. Nous sommes à votre demande",
    },
    renderSubmitMessageContent: {
      successMessage: "Demande effectuée avec succès",
      clientErrorMessage: "Erreur de téléchargement. Veuillez réessayer",
      serverErrorMessage: "Le téléchargement a échoué. Veuillez réessayer",
      goBack: "retourner",
    },
    renderRequestSectionContent: {
      heading: "Faire une demande par",
      myFileText: "Votre navigateur ne prend pas en charge la balise vidéo",
      uploadVideoText: "Cliquez ici pour télécharger votre vidéo",
      uploadThumbnailText: "Cliquez ici pour télécharger votre miniature",
      title_: "Titre (obligatoire)",
      description_: "Description (obligatoire)",
      titlePlaceHolder: "Ajoutez un titre qui décrit votre vidéo",
      descriptionPlaceHolder: "Parlez aux spectateurs de votre vidéo",
      audience_: "Public (obligatoire)",
      madeForKids: "Oui, fait pour les enfants",
      notMadeForKids: "Non, pas fait pour les enfants",
      visibility_: "Visibilité (obligatoire)",
      selectVisibility: "Sélectionnez la visibilité",
      public_: "public",
      private_: "privé",
      category: "Catégorie (obligatoire)",
      selectCategory: "Choisir une catégorie",
      creatorInvitationCode: "Code d'invitation du créateur (obligatoire)",
      creatorIdPlaceHolder:'identifiant du créateur',
      submit: "Soumettre",
    },
  },
  AR: {
    renderLoadingContent: {
      loadingText: "انتظر من فضلك. نحن على طلبك",
    },
    renderSubmitMessageContent: {
      successMessage: "تم الطلب بنجاح",
      clientErrorMessage: "حدث خطأ أثناء التحميل. حاول مرة اخرى",
      serverErrorMessage: "التحميل فشل. حاول مرة اخرى",
      goBack: "عُد",
    },
    renderRequestSectionContent: {
      heading: "تقديم طلب بواسطة",
      myFileText: "متصفحك الحالي لا يدعم تشغيل الفيديو",
      uploadVideoText: "انقر هنا لتحميل الفيديو الخاص بك",
      uploadThumbnailText: "انقر هنا لتحميل الصورة المصغرة الخاصة بك",
      title_: "العنوان (مطلوب)",
      description_: "الوصف (مطلوب)",
      titlePlaceHolder: "أضف عنوانًا يصف الفيديو الخاص بك",
      descriptionPlaceHolder: "أخبر المشاهدين عن الفيديو الخاص بك",
      audience_: "الجمهور(مطلوب)",
      madeForKids: "نعم، صنعت للأطفال",
      notMadeForKids: "لا، غير مخصص للأطفال",
      visibility_: "الرؤية (مطلوب)",
      selectVisibility: "حدد إمكانية الرؤية",
      public_: "عام",
      private_: "خاص",
      category: "الفئة (مطلوب)",
      selectCategory: "اختر الفئة",
      creatorInvitationCode: "رمز دعوة منشئ المحتوى (مطلوب)",
      creatorIdPlaceHolder:'معرف الخالق',
      submit: "يُقدِّم",
    },
  },
  BN: {
    renderLoadingContent: {
      loadingText: "অনুগ্রহপূর্বক অপেক্ষা করুন। আমরা আপনার অনুরোধে আছি",
    },
    renderSubmitMessageContent: {
      successMessage: "অনুরোধ সফলভাবে করা হয়েছে",
      clientErrorMessage:
        "আপলোড করার সময় ত্রুটি। অনুগ্রহপূর্বক আবার চেষ্টা করুন",
      serverErrorMessage: "আপলোড ব্যর্থ হয়েছে। অনুগ্রহপূর্বক আবার চেষ্টা করুন",
      goBack: "ফিরে যাও",
    },
    renderRequestSectionContent: {
      heading: "দ্বারা একটি অনুরোধ করুন",
      myFileText: "আপনার ব্রাউজার ভিডিও ট্যাগ সমর্থন করে না",
      uploadVideoText: "আপনার ভিডিও আপলোড করতে এখানে ক্লিক করুন",
      uploadThumbnailText: "আপনার থাম্বনেইল আপলোড করতে এখানে ক্লিক করুন",
      title_: "শিরোনাম (প্রয়োজনীয়)",
      description_: "বর্ণনা (প্রয়োজনীয়)",
      titlePlaceHolder: "আপনার ভিডিও বর্ণনা করে এমন একটি শিরোনাম যোগ করুন",
      descriptionPlaceHolder: "আপনার ভিডিও সম্পর্কে দর্শকদের বলুন",
      audience_: "দর্শক (প্রয়োজনীয়)",
      madeForKids: "হ্যাঁ, বাচ্চাদের জন্য তৈরি",
      notMadeForKids: "না, বাচ্চাদের জন্য তৈরি নয়",
      visibility_: "দৃশ্যমানতা",
      selectVisibility: "দৃশ্যমানতা নির্বাচন করুন",
      public_: "পাবলিক",
      private_: "ব্যক্তিগত",
      category: "বিভাগ (প্রয়োজনীয়)",
      selectCategory: "বিভাগ নির্বাচন করুন",
      creatorInvitationCode: "সৃষ্টিকর্তার আমন্ত্রণ কোড (প্রয়োজনীয়)",
      creatorIdPlaceHolder:'নির্মাতা আইডি',
      submit: "জমা দিন",
    },
  },
  RU: {
    renderLoadingContent: {
      loadingText: "Пожалуйста, подождите. Мы по вашему запросу",
    },
    renderSubmitMessageContent: {
      successMessage: "Запрос выполнен успешно",
      clientErrorMessage: "Ошибка загрузки. Пожалуйста, попробуйте еще раз",
      serverErrorMessage: "Загрузка не удалась. Пожалуйста, попробуйте еще раз",
      goBack: "возвращаться",
    },
    renderRequestSectionContent: {
      heading: "Сделать запрос",
      myFileText: "Ваш браузер не поддерживает видео тег",
      uploadVideoText: "Нажмите здесь, чтобы загрузить свое видео",
      uploadThumbnailText: "Нажмите здесь, чтобы загрузить миниатюру",
      title_: "Название (обязательно)",
      description_: "Описание (обязательно)",
      titlePlaceHolder: "Добавьте заголовок, описывающий ваше видео",
      descriptionPlaceHolder: "Расскажите зрителям о своем видео",
      audience_: "Аудитория (обязательно)",
      madeForKids: "Да, сделано для детей",
      notMadeForKids: "Нет, не для детей",
      visibility_: "Видимость (обязательно)",
      selectVisibility: "Выберите Видимость",
      public_: "общественный",
      private_: "частный",
      category: "Категория (обязательно)",
      selectCategory: "выберите категорию",
      creatorInvitationCode: "Пригласительный код автора (обязательно)",
      creatorIdPlaceHolder:'идентификатор создателя',
      submit: "подавать",
    },
  },
  PT: {
    renderLoadingContent: {
      loadingText: "Por favor, aguarde. Estamos a seu pedido",
    },
    renderSubmitMessageContent: {
      successMessage: "Solicitação realizada com sucesso",
      clientErrorMessage: "Erro ao carregar. Por favor, tente novamente",
      serverErrorMessage: "Falha no upload. Por favor, tente novamente",
      goBack: "volte",
    },
    renderRequestSectionContent: {
      heading: "Faça uma solicitação por",
      myFileText: "Seu navegador não suporta a tag de vídeo",
      uploadVideoText: "Clique aqui para enviar seu vídeo",
      uploadThumbnailText: "Clique aqui para enviar sua miniatura",
      title_: "Título (obrigatório)",
      description_: "Descrição (obrigatório)",
      titlePlaceHolder: "Adicione um título que descreva seu vídeo",
      descriptionPlaceHolder: "Conte aos espectadores sobre seu vídeo",
      audience_: "Público-alvo (obrigatório)",
      madeForKids: "Sim, feito para crianças",
      notMadeForKids: "Não, não foi feito para crianças",
      visibility_: "Visibilidade (obrigatório)",
      selectVisibility: "Selecione Visibilidade",
      public_: "público",
      private_: "privado",
      category: "Categoria (obrigatório)",
      selectCategory: "Selecione a Categoria",
      creatorInvitationCode: "Código de convite do criador (obrigatório)",
      creatorIdPlaceHolder:'ID do criador',
      submit: "Enviar",
    },
  },
  UR: {
    renderLoadingContent: {
      loadingText: "Por favor, aguarde. Estamos a seu pedido",
    },
    renderSubmitMessageContent: {
      successMessage: "Solicitação realizada com sucesso",
      clientErrorMessage: "Erro ao carregar. Por favor, tente novamente",
      serverErrorMessage: "Falha no upload. Por favor, tente novamente",
      goBack: "volte",
    },
    renderRequestSectionContent: {
      heading: "Faça uma solicitação por",
      myFileText:
        "Seu navegador não suporta a tag de vídeoSeu navegador não suporta a tag de vídeo",
      uploadVideoText: "Clique aqui para enviar seu vídeo",
      uploadThumbnailText: "Clique aqui para enviar sua miniatura",
      title_: "Título (obrigatório)",
      description_: "Descrição (obrigatório)",
      titlePlaceHolder: "ایک عنوان شامل کریں جو آپ کے ویڈیو کی وضاحت کرتا ہو۔",
      descriptionPlaceHolder: "ناظرین کو اپنی ویڈیو کے بارے میں بتائیں",
      audience_: "Público-alvo (obrigatório)",
      madeForKids: "Sim, feito para crianças",
      notMadeForKids: "Não, não foi feito para crianças",
      visibility_: "Visibilidade (obrigatório)",
      selectVisibility: "مرئیت کو منتخب کریں۔",
      public_: "público",
      private_: "privado",
      category: "Categoria (obrigatório)",
      selectCategory: "Selecione a Categoria",
      creatorInvitationCode: "Código de convite do criador (obrigatório)",
      creatorIdPlaceHolder:'تخلیق کار کی شناخت',
      submit: "Enviar",
    },
  },
};

export const youtubeCategoriesContainer = {
  EN: [
    { category: "Film & Animation", id: 1 },
    { category: "Autos & Vehicles", id: 2 },
    { category: "Music", id: 10 },
    { category: "Pets & Animals", id: 15 },
    { category: "Sports", id: 17 },
    { category: "Short Movies", id: 18 },
    { category: "Travel & Events", id: 19 },
    { category: "Gaming", id: 20 },
    { category: "Videoblogging", id: 21 },
    { category: "People & Blogs", id: 22 },
    { category: "Comedy", id: 23 },
    { category: "Entertainment", id: 24 },
    { category: "News & Politics", id: 25 },
    { category: "Howto & Style", id: 26 },
    { category: "Education", id: 27 },
    { category: "Science & Technology", id: 28 },
    { category: "Nonprofits & Activism", id: 29 },
    { category: "Movies", id: 30 },
    { category: "Anime/Animation", id: 31 },
    { category: "Action/Adventure", id: 32 },
    { category: "Classics", id: 33 },
    { category: "Documentary", id: 35 },
    { category: "Drama", id: 36 },
    { category: "Family", id: 37 },
    { category: "Foreign", id: 38 },
    { category: "Horror", id: 39 },
    { category: "Sci-Fi/Fantasy", id: 40 },
    { category: "Thriller", id: 41 },
    { category: "Shorts", id: 42 },
    { category: "Shows", id: 43 },
    { category: "Trailers", id: 44 },
  ],
  HI: [
    { category: "फ़िल्म एवं एनिमेशन", id: 1 },
    { category: "ऑटो और वाहन", id: 2 },
    { category: "संगीत", id: 10 },
    { category: "पालतू पशु", id: 15 },
    { category: "खेल", id: 17 },
    { category: "लघु फिल्में", id: 18 },
    { category: "यात्रा एवं घटनाक्रम", id: 19 },
    { category: "जुआ", id: 20 },
    { category: "वीडियोब्लॉगिंग", id: 21 },
    { category: "लोग और ब्लॉग", id: 22 },
    { category: "कॉमेडी", id: 23 },
    { category: "मनोरंजन", id: 24 },
    { category: "समाचार और राजनीति", id: 25 },
    { category: "मनोहर ढंग से कैसे करें", id: 26 },
    { category: "शिक्षा", id: 27 },
    { category: "विज्ञान प्रौद्योगिकी", id: 28 },
    { category: "गैर-लाभकारी संस्थाएँ और सक्रियता", id: 29 },
    { category: "चलचित्र", id: 30 },
    { category: "एनीमे/एनीमेशन", id: 31 },
    { category: "एक्शन एडवेंचर", id: 32 },
    { category: "कुंआरियां", id: 33 },
    { category: "दस्तावेज़ी", id: 35 },
    { category: "नाटक", id: 36 },
    { category: "परिवार", id: 37 },
    { category: "विदेश", id: 38 },
    { category: "डरावनी", id: 39 },
    { category: "विज्ञान-कथा/काल्पनिक", id: 40 },
    { category: "थ्रिलर", id: 41 },
    { category: "निकर", id: 42 },
    { category: "दिखाता है", id: 43 },
    { category: "ट्रेलरों", id: 44 },
  ],
  TE: [
    { category: "ఫిల్మ్ & యానిమేషన్", id: 1 },
    { category: "ఆటోలు & వాహనాలు", id: 2 },
    { category: "సంగీతం", id: 10 },
    { category: "పెంపుడు జంతువులు & జంతువులు", id: 15 },
    { category: "క్రీడలు", id: 17 },
    { category: "చిన్న సినిమాలు", id: 18 },
    { category: "ప్రయాణం & ఈవెంట్‌లు", id: 19 },
    { category: "గేమింగ్", id: 20 },
    { category: "వీడియోబ్లాగింగ్", id: 21 },
    { category: "వ్యక్తులు & బ్లాగులు", id: 22 },
    { category: "హాస్యం", id: 23 },
    { category: "వినోదం", id: 24 },
    { category: "వార్తలు & రాజకీయాలు", id: 25 },
    { category: "ఎలా & శైలి", id: 26 },
    { category: "చదువు", id: 27 },
    { category: "సైన్స్ & టెక్నాలజీ", id: 28 },
    { category: "లాభాపేక్ష రహిత సంస్థలు & క్రియాశీలత", id: 29 },
    { category: "సినిమాలు", id: 30 },
    { category: "అనిమే/యానిమేషన్", id: 31 },
    { category: "యాక్షన్/సాహసం", id: 32 },
    { category: "క్లాసిక్స్", id: 33 },
    { category: "డాక్యుమెంటరీ", id: 35 },
    { category: "నాటకం", id: 36 },
    { category: "కుటుంబం", id: 37 },
    { category: "విదేశీ", id: 38 },
    { category: "భయానక", id: 39 },
    { category: "భయానక", id: 40 },
    { category: "థ్రిల్లర్", id: 41 },
    { category: "లఘు చిత్రాలు", id: 42 },
    { category: "ప్రదర్శనలు", id: 43 },
    { category: "ట్రైలర్స్", id: 44 },
  ],
  ZH: [
    { category: "電影與動畫", id: 1 },
    { category: "汽車及交通工具", id: 2 },
    { category: "音樂", id: 10 },
    { category: "寵物與動物", id: 15 },
    { category: "運動的", id: 17 },
    { category: "短片", id: 18 },
    { category: "旅行與活動", id: 19 },
    { category: "賭博", id: 20 },
    { category: "視訊部落格", id: 21 },
    { category: "人物與部落格", id: 22 },
    { category: "喜劇", id: 23 },
    { category: "娛樂", id: 24 },
    { category: "新聞與政治", id: 25 },
    { category: "操作方法與風格", id: 26 },
    { category: "教育", id: 27 },
    { category: "科學技術", id: 28 },
    { category: "非營利組織與行動主義", id: 29 },
    { category: "電影", id: 30 },
    { category: "動漫/動畫", id: 31 },
    { category: "動作/冒險", id: 32 },
    { category: "經典", id: 33 },
    { category: "記錄", id: 35 },
    { category: "戲劇", id: 36 },
    { category: "家庭", id: 37 },
    { category: "外國的", id: 38 },
    { category: "恐怖", id: 39 },
    { category: "科幻/奇幻", id: 40 },
    { category: "驚悚片", id: 41 },
    { category: "短褲", id: 42 },
    { category: "演出", id: 43 },
    { category: "拖車", id: 44 },
  ],
  ES: [
    { category: "Cine y Animación", id: 1 },
    { category: "Autos y Vehículos", id: 2 },
    { category: "Música", id: 10 },
    { category: "Animales de compañía", id: 15 },
    { category: "Deportes", id: 17 },
    { category: "Películas cortas", id: 18 },
    { category: "Viajes y Eventos", id: 19 },
    { category: "Juego de azar", id: 20 },
    { category: "Videoblogging", id: 21 },
    { category: "Personas y blogs", id: 22 },
    { category: "Comedia", id: 23 },
    { category: "Entretenimiento", id: 24 },
    { category: "Noticias y política", id: 25 },
    { category: "Cómo y estilo", id: 26 },
    { category: "Educación", id: 27 },
    { category: "Tecnología científica", id: 28 },
    { category: "Organizaciones sin fines de lucro y activismo", id: 29 },
    { category: "Películas", id: 30 },
    { category: "Anime/Animación", id: 31 },
    { category: "Acción Aventura", id: 32 },
    { category: "Clásicos", id: 33 },
    { category: "Documental", id: 35 },
    { category: "Drama", id: 36 },
    { category: "Familia", id: 37 },
    { category: "Extranjero", id: 38 },
    { category: "Horror", id: 39 },
    { category: "Ciencia ficción/fantasía", id: 40 },
    { category: "Suspenso", id: 41 },
    { category: "Bermudas", id: 42 },
    { category: "Espectáculos", id: 43 },
    { category: "Remolques", id: 44 },
  ],
  FR: [
    { category: "Cinéma et animation", id: 1 },
    { category: "Automobiles et véhicules", id: 2 },
    { category: "Musique", id: 10 },
    { category: "Animaux et animaux", id: 15 },
    { category: "Des sports", id: 17 },
    { category: "Courts métrages", id: 18 },
    { category: "Voyages et événements", id: 19 },
    { category: "Jeux", id: 20 },
    { category: "Blog vidéo", id: 21 },
    { category: "Personnes et blogs", id: 22 },
    { category: "Comédie", id: 23 },
    { category: "Divertissement", id: 24 },
    { category: "Actualités et politique", id: 25 },
    { category: "Comment styliser", id: 26 },
    { category: "Éducation", id: 27 },
    { category: "Technologie scientifique", id: 28 },
    { category: "Organisations à but non lucratif et militantisme", id: 29 },
    { category: "Films", id: 30 },
    { category: "Anime/Animation", id: 31 },
    { category: "Action/Aventure", id: 32 },
    { category: "Classiques", id: 33 },
    { category: "Documentaire", id: 35 },
    { category: "Drame", id: 36 },
    { category: "Famille", id: 37 },
    { category: "Étranger", id: 38 },
    { category: "Horreur", id: 39 },
    { category: "Science-fiction/Fantastique", id: 40 },
    { category: "Thriller", id: 41 },
    { category: "Shorts", id: 42 },
    { category: "Montre", id: 43 },
    { category: "Bandes annonces", id: 44 },
  ],
  AR: [
    { category: "السينما والرسوم المتحركة", id: 1 },
    { category: "السيارات والمركبات", id: 2 },
    { category: "موسيقى", id: 10 },
    { category: "الحيوانات الأليفة الحيوانات", id: 15 },
    { category: "رياضات", id: 17 },
    { category: "أفلام قصيرة", id: 18 },
    { category: "السفر والأحداث", id: 19 },
    { category: "الألعاب", id: 20 },
    { category: "تدوين الفيديو", id: 21 },
    { category: "الناس والمدونات", id: 22 },
    { category: "كوميديا", id: 23 },
    { category: "ترفيه", id: 24 },
    { category: "الأخبار والسياسة", id: 25 },
    { category: "كيف تصمم", id: 26 },
    { category: "تعليم", id: 27 },
    { category: "العلوم والتكنولوجيا", id: 28 },
    { category: "المنظمات غير الربحية والنشاط", id: 29 },
    { category: "أفلام", id: 30 },
    { category: "أنيمي / الرسوم المتحركة", id: 31 },
    { category: "عمل مغامرة", id: 32 },
    { category: "الكلاسيكيات", id: 33 },
    { category: "وثائقي", id: 35 },
    { category: "دراما", id: 36 },
    { category: "عائلة", id: 37 },
    { category: "أجنبي", id: 38 },
    { category: "رعب", id: 39 },
    { category: "خيال علمي/فانتازيا", id: 40 },
    { category: "إثارة", id: 41 },
    { category: "السراويل القصيرة", id: 42 },
    { category: "عروض", id: 43 },
    { category: "مقطورات", id: 44 },
  ],
  BN: [
    { category: "ফিল্ম এবং অ্যানিমেশন", id: 1 },
    { category: "অটো এবং যানবাহন", id: 2 },
    { category: "সঙ্গীত", id: 10 },
    { category: "পোষা প্রাণী এবং প্রাণী", id: 15 },
    { category: "খেলাধুলা", id: 17 },
    { category: "শর্ট মুভি", id: 18 },
    { category: "ভ্রমণ ও ঘটনা", id: 19 },
    { category: "গেমিং", id: 20 },
    { category: "ভিডিওব্লগিং", id: 21 },
    { category: "মানুষ এবং ব্লগ", id: 22 },
    { category: "কমেডি", id: 23 },
    { category: "বিনোদন", id: 24 },
    { category: "সংবাদ ও রাজনীতি", id: 25 },
    { category: "কিভাবে এবং শৈলী", id: 26 },
    { category: "শিক্ষা", id: 27 },
    { category: "বিজ্ঞান প্রযুক্তি", id: 28 },
    { category: "অলাভজনক এবং সক্রিয়তা", id: 29 },
    { category: "সিনেমা", id: 30 },
    { category: "অ্যানিমে/অ্যানিমেশন", id: 31 },
    { category: "কর্ম দু: সাহসিক কাজ", id: 32 },
    { category: "ক্লাসিক", id: 33 },
    { category: "তথ্যচিত্র", id: 35 },
    { category: "নাটক", id: 36 },
    { category: "পরিবার", id: 37 },
    { category: "বিদেশী", id: 38 },
    { category: "হরর", id: 39 },
    { category: "সাই-ফাই/ফ্যান্টাসি", id: 40 },
    { category: "থ্রিলার", id: 41 },
    { category: "শর্টস", id: 42 },
    { category: "দেখায়", id: 43 },
    { category: "ট্রেলার", id: 44 },
  ],
  RU: [
    { category: "Кино и анимация", id: 1 },
    { category: "Автомобили и транспортные средства", id: 2 },
    { category: "Музыка", id: 10 },
    { category: "Домашние животные и животные", id: 15 },
    { category: "Виды спорта", id: 17 },
    { category: "Короткометражные фильмы", id: 18 },
    { category: "Путешествия и события", id: 19 },
    { category: "Игры", id: 20 },
    { category: "Видеоблоги", id: 21 },
    { category: "Люди и Блоги", id: 22 },
    { category: "Комедия", id: 23 },
    { category: "Развлечение", id: 24 },
    { category: "Новости и политика", id: 25 },
    { category: "Как и стиль", id: 26 },
    { category: "Образование", id: 27 },
    { category: "Научная технология", id: 28 },
    { category: "Некоммерческие организации и активизм", id: 29 },
    { category: "Кино", id: 30 },
    { category: "Аниме/Анимация", id: 31 },
    { category: "Боевик/Приключение", id: 32 },
    { category: "Классика", id: 33 },
    { category: "Документальный", id: 35 },
    { category: "Драма", id: 36 },
    { category: "Семья", id: 37 },
    { category: "Иностранный", id: 38 },
    { category: "Ужастик", id: 39 },
    { category: "Научная фантастика/фэнтези", id: 40 },
    { category: "Триллер", id: 41 },
    { category: "Шорты", id: 42 },
    { category: "Шоу", id: 43 },
    { category: "Трейлеры", id: 44 },
  ],
  PT: [
    { category: "Filme e Animação", id: 1 },
    { category: "Automóveis e veículos", id: 2 },
    { category: "Música", id: 10 },
    { category: "Animais de estimacao", id: 15 },
    { category: "Esportes", id: 17 },
    { category: "Curtas-metragens", id: 18 },
    { category: "Viagens e Eventos", id: 19 },
    { category: "Jogos", id: 20 },
    { category: "Videoblog", id: 21 },
    { category: "Pessoas e blogs", id: 22 },
    { category: "Comédia", id: 23 },
    { category: "Entretenimento", id: 24 },
    { category: "Notícias e Política", id: 25 },
    { category: "Como estilizar", id: 26 },
    { category: "Educação", id: 27 },
    { category: "Tecnologia científica", id: 28 },
    { category: "Organizações sem fins lucrativos e ativismo", id: 29 },
    { category: "Filmes", id: 30 },
    { category: "Anime/Animação", id: 31 },
    { category: "Ação e aventura", id: 32 },
    { category: "Clássicos", id: 33 },
    { category: "Documentário", id: 35 },
    { category: "Drama", id: 36 },
    { category: "Família", id: 37 },
    { category: "Estrangeiro", id: 38 },
    { category: "Horror", id: 39 },
    { category: "Ficção Científica/Fantasia", id: 40 },
    { category: "Filme de ação", id: 41 },
    { category: "Shorts", id: 42 },
    { category: "Programas", id: 43 },
    { category: "trechos de um filme", id: 44 },
  ],
  UR: [
    { category: "فلم اور حرکت پذیری۔", id: 1 },
    { category: "آٹوز اور گاڑیاں", id: 2 },
    { category: "موسیقی", id: 10 },
    { category: "پالتو جانور اور جانور", id: 15 },
    { category: "کھیل", id: 17 },
    { category: "مختصر فلمیں", id: 18 },
    { category: "سفر اور واقعات", id: 19 },
    { category: "گیمنگ", id: 20 },
    { category: "ویڈیو بلاگنگ", id: 21 },
    { category: "لوگ اور بلاگز", id: 22 },
    { category: "کامیڈی", id: 23 },
    { category: "تفریح", id: 24 },
    { category: "خبریں اور سیاست", id: 25 },
    { category: "طریقہ اور انداز", id: 26 },
    { category: "تعلیم", id: 27 },
    { category: "سائنس ٹیکنالوجی", id: 28 },
    { category: "غیر منفعتی اور سرگرمی", id: 29 },
    { category: "فلمیں", id: 30 },
    { category: "اینیمی/اینیمیشن", id: 31 },
    { category: "ایکشن/ایڈونچر", id: 32 },
    { category: "کلاسیکی", id: 33 },
    { category: "دستاویزی فلم", id: 35 },
    { category: "ڈرامہ", id: 36 },
    { category: "خاندان", id: 37 },
    { category: "غیر ملکی", id: 38 },
    { category: "وحشت", id: 39 },
    { category: "سائنس فائی/فنٹیسی", id: 40 },
    { category: "تھرلر", id: 41 },
    { category: "شارٹس", id: 42 },
    { category: "دکھاتا ہے۔", id: 43 },
    { category: "ٹریلرز", id: 44 },
  ],
};

export const youtubeCategories = [
  { category: "Film & Animation", id: 1 },
  { category: "Autos & Vehicles", id: 2 },
  { category: "Music", id: 10 },
  { category: "Pets & Animals", id: 15 },
  { category: "Sports", id: 17 },
  { category: "Short Movies", id: 18 },
  { category: "Travel & Events", id: 19 },
  { category: "Gaming", id: 20 },
  { category: "Videoblogging", id: 21 },
  { category: "People & Blogs", id: 22 },
  { category: "Comedy", id: 23 },
  { category: "Entertainment", id: 24 },
  { category: "News & Politics", id: 25 },
  { category: "Howto & Style", id: 26 },
  { category: "Education", id: 27 },
  { category: "Science & Technology", id: 28 },
  { category: "Nonprofits & Activism", id: 29 },
  { category: "Movies", id: 30 },
  { category: "Anime/Animation", id: 31 },
  { category: "Action/Adventure", id: 32 },
  { category: "Classics", id: 33 },
  { category: "Documentary", id: 35 },
  { category: "Drama", id: 36 },
  { category: "Family", id: 37 },
  { category: "Foreign", id: 38 },
  { category: "Horror", id: 39 },
  { category: "Sci-Fi/Fantasy", id: 40 },
  { category: "Thriller", id: 41 },
  { category: "Shorts", id: 42 },
  { category: "Shows", id: 43 },
  { category: "Trailers", id: 44 },
];
